apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nodecheck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodecheck
  template:
    metadata:
      labels:
        app: nodecheck
    spec:
      containers:
      - image: nodecheck:release-1.0.0
        imagePullPolicy: Always
        name: nodecheck
